name: Combine Text and Release

on:
  push:
    # Only trigger if files inside this specific folder are modified
    paths:
      - 'autoplaylist/*.txt'
    branches:
      - main
  workflow_dispatch: # Keeps the manual "Run Workflow" button active

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Script
        run: chmod +x ./combine_text.sh

      - name: Combine autoplaylist entries
        # Matches the 'paths' filter above
        run: mkdir ./output && ./combine_text.sh ./autoplaylist ./output/autoplaylist.txt && ./combine_text.sh -c ./autoplaylist ./output/autoplaylist-flat.txt

      - name: Upload autoplaylist
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.repository_id }}-build-libs
          path: /output/autoplaylist.txt
          archive: false
          retention-days: 90

      - name: Upload flat autoplaylist
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.repository_id }}-build-libs
          path: /output/autoplaylist-flat.txt
          archive: false
          retention-days: 90